Create Recipe App with Rails
alonsofl/recipe-app pull request #24
Opened 2021-11-17 21:36 UTC by alonsofl

## Summary
Created a Recipe App with Rails that allow users to add food(ingredients) and recipes. This app uses authorization to delete and update each recipe and/or food(ingredients).

#### Details
- Installed Ruby on Rails framework.
- Created migration files according to the [ERD Diagram](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/images/recipe_app_erd.png)
- Added the required routes to recipes, foods, shopping lists, and forms to register, login, and add items.
- Configured controllers to handle requests.
- Added the required models and validations.
- Added Devise, CanCanCan, RSpec, and Capybara gems.
- Added the required views for each controller and route.
- Secured the app from n+1 problems.
- Added testing to the project.

2021-11-17 22:13 UTC, DeliceLydia requested changes
## Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [ ] Because this project is collaborative you should all participate I can see that all commits were done by one person this is not professional because collaborating will prepare you in your future endeavors, please next time don't do this

### Cheers and Happy coding!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-17 22:13 UTC, DeliceLydia commented on README.md
> +- LinkedIn - [Alonso Falconi](https://www.linkedin.com/in/bimbolabuari/)
- [ ] Add the right author account

2021-11-17 22:13 UTC, DeliceLydia commented on README.md
> +- LinkedIn - [Alonso Falconi](https://www.linkedin.com/in/bimbolabuari/)
- [ ] Please add a live demo in your README

2021-11-17 23:15 UTC, alonsofl commented on README.md
> +- LinkedIn - [Alonso Falconi](https://www.linkedin.com/in/bimbolabuari/)
Thanks for your review! The suggestions have been addressed :smiley:

2021-11-18 01:14 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2021-11-18 04:28 UTC, alonsofl commented
Thanks, guys! :raised_hands:

2021-11-18 04:28 UTC, merged